bot:
  token: "1115228165:AAHM98pxQtMTUFgoGtMQVRCU5y4ALuFtNSg"

SRO_types:
  - "СРО в области строительства"
  - "СРО в области проектирования"

templates:
  hello: "Выберите СРО, в которое желаете подать заявку"
  need_close_request: "Сначала необходимо завершить предыдущую заявку или отменить ее"
  need_fio: "Отправьте одним сообщением полное ФИО"
  need_org: "Отправьте название Вашей организации"
  need_email: "Отправьте Ваш контактный email"
  need_phone: "Отправьте Ваш контактный номер телефона"
  need_region: "Выберите Ваш регион. Если он отсутвует в списке, можете отправить его название в сообщении"
  need_check_projects: "Подтвердите правильность информации:\n\nОрганизация: {org}\nФИО: {fio}\nemail: {email}\nТелефон: {phone}"
  need_check_builders: "Подтвердите правильность информации:\n\nОрганизация: {org}\nФИО: {fio}\nemail: {email}\nТелефон: {phone}\nРегион: {region}"
  success: "Заявка на вступление в *{purpes}* оформлена.\nВ скором времени с вами свяжется ответсвенный менеджер."
  drop: "Составление заявки отменено.\nВыберите СРО, к которому желаете присоединиться"
  nothing_to_success: "Нечего подтверждать"
  nothing_to_drop: "Нечего отменять"

cities:
  - [Иваново, Москва]
  - [Владимир, Ярославль]
  - [Кострома, Нижний Новгород]
  # - Воронеж
  # - Белгород
  # - Тула
  # - Тверь
  # - Брянск
  # - Липецк
  # - Рязань
  # - Курск
  # - Тамбов
  # - Калуга
  # - Смоленск
  # - Орел